class DataItems {
  List<String> dist = [
    "Cachar",
    "Goalpara",
    "Jorhat",
    "Karbi Anglong",
    "Kokrajhar",
    "Lakhimpur",
    "MORIGAON",
    "Nalbari",
    "Sibsagar",
    "Banka",
    "Rohtas",
    "Balodabazar",
    "Bilaspur",
    "Jashpur",
    "Kanker",
    "Kondagaon",
    "Mahasamund",
    "South Goa",
    "Amreli",
    "Anand",
    "Banaskanth",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Devbhumi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagarh",
    "Kheda",
    "Mehsana",
    "Morbi",
    "Navsari",
    "Panchmahals",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha",
    "Surat",
    "Surendranagar",
    "Vadodara(Baroda)",
    "Ambala",
    "Faridabad",
    "Gurgaon",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh-Narnaul",
    "Panipat",
    "Sirsa",
    "Sonipat",
    "Anantnag",
    "Badgam",
    "Jammu",
    "Kathua",
    "Rajouri",
    "Srinagar",
    "Udhampur",
    "Chamrajnagar",
    "Gadag",
    "Mandya",
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasargod",
    "Kollam",
    "Kottayam",
    "Kozhikode(Calicut)",
    "Malappuram",
    "Palakad",
    "Pathanamthitta",
    "Thirssur",
    "Thiruvananthapuram",
    "Alirajpur",
    "Anupur",
    "Badwani",
    "Bhopal",
    "Chhatarpur",
    "Damoh",
    "Dhar",
    "Dindori",
    "Gwalior",
    "Hoshangabad",
    "Indore",
    "Khargone",
    "Mandla",
    "Morena",
    "Rajgarh",
    "Rewa",
    "Sagar",
    "Sidhi",
    "Ujjain",
    "Umariya",
    "Ahmednagar",
    "Amarawati",
    "Beed",
    "Buldhana",
    "Chandrapur",
    "Chattrapati Sambhajinagar",
    "Dhule",
    "Gadchiroli",
    "Jalgaon",
    "Kolhapur",
    "Nagpur",
    "Pune",
    "Raigad",
    "Sangli",
    "Satara",
    "Sholapur",
    "Delhi",
    "Balasore",
    "Dhenkanal",
    "Gajapati",
    "Jharsuguda",
    "Bhatinda",
    "Fazilka",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Ludhiana",
    "Patiala",
    "Sangrur",
    "Tarntaran",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Ganganagar",
    "Hanumangarh",
    "Jaipur Rural",
    "Jodhpur",
    "Tonk",
    "Ariyalur",
    "Chengalpattu",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakuruchi",
    "Kancheepuram",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Nagapattinam",
    "Nagercoil (Kannyiakumari)",
    "Namakkal",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "The Nilgiris",
    "Theni",
    "Thiruchirappalli",
    "Thirunelveli",
    "Thirupathur",
    "Thirupur",
    "Thiruvannamalai",
    "Thiruvarur",
    "Thiruvellore",
    "Tuticorin",
    "Vellore",
    "Villupuram",
    "Virudhunagar",
    "Adilabad",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Medak",
    "Nalgonda",
    "Ranga Reddy",
    "Warangal",
    "Dhalai",
    "Unokoti",
    "Agra",
    "Aligarh",
    "Amroha",
    "Baghpat",
    "Bahraich",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Bulandshahar",
    "Farukhabad",
    "Fatehpur",
    "Gorakhpur",
    "Hamirpur",
    "Hathras",
    "Jalaun (Orai)",
    "Jaunpur",
    "Jhansi",
    "Lalitpur",
    "Mainpuri",
    "Mirzapur",
    "Muzaffarnagar",
    "Raebarelli",
    "Shahjahanpur",
    "Siddharth Nagar",
    "Sitapur",
    "Unnao",
    "Haridwar",
    "UdhamSinghNagar",
    "Bankura",
    "Birbhum",
    "Darjeeling",
    "Howrah",
    "Medinipur(W)",
    "Nadia",
    "Paschim Bardhaman",
    "Puruliya",
    "Visakhapatnam",
    "Kamrup",
    "Nagaon",
    "Jamui",
    "Kaithar",
    "Patna",
    "Samastipur",
    "Dhamtari",
    "Rajnandgaon",
    "Ahmedabad",
    "Mewat",
    "Panchkula",
    "Pulwama",
    "Kolar",
    "Balaghat",
    "Jhabua",
    "Panna",
    "Shajapur",
    "Shehdol",
    "Jalana",
    "Nashik",
    "Yavatmal",
    "Sanchore",
    "Ambedkarnagar",
    "Badaun",
    "Bijnor",
    "Etawah",
    "Lucknow",
    "Prayagraj",
    "Sambhal",
    "Bhojpur",
    "Narayanpur",
    "Raigarh",
    "Palwal",
    "Kupwara",
    "Harda",
    "Jabalpur",
    "Katni",
    "Khandwa",
    "Seoni",
    "Sheopur",
    "Vidisha",
    "Hingoli",
    "Nanded",
    "Puri",
    "Amritsar",
    "Gomati",
    "Rampur",
    "Madhubani",
    "Janjgir",
    "Kachchh",
    "Narmada",
    "Haveri",
    "Raisen",
    "Tikamgarh",
    "Jhunjhunu",
    "Mahoba",
    "Chittor",
    "Araria",
    "Korba",
    "Koria",
    "Bhiwani",
    "Kaithal",
    "Dewas",
    "Satna",
    "Sehore",
    "Shivpuri",
    "Hardoi",
    "Champawat"
  ];

  List<String> state = [
    "Assam",
    "Bihar",
    "Chattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "NCT of Delhi",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttrakhand",
    "West Bengal",
    "Andhra Pradesh"
  ];

  List<String> market = [
    'Kashipur',
    'Jaleswar',
    'Mariani',
    'Sariahjan',
    'Gossaigaon',
    'Ghilamara',
    'Moirabari',
    'Dhamdhama',
    'Sibsagar',
    'Barahat',
    'Kochas (Balthari)',
    'Sarsiwan',
    'Tiphra',
    'Pathalgaon',
    'Charama',
    'Hirapur',
    'Bhoring',
    'Curchorem',
    'Amreli',
    'Bagasara',
    'Rajula',
    'Savarkundla',
    'Khambhat(Veg Yard Khambhat)',
    'Deesa',
    'Deesa(Deesa Veg Yard)',
    'Bhavnagar',
    'Taleja',
    'Botad',
    'Hadad',
    'Kalediya',
    'Dahod',
    'Dahod(Veg. Market)',
    'Davgadbaria(Piplod)',
    'Zalod(Sanjeli)',
    'Bhanvad',
    'Dehgam',
    'Dehgam(Rekhiyal)',
    'Kalol',
    'Mansa',
    'Mansa(Manas Veg Yard)',
    'Talalagir',
    'Veraval',
    'Dhrol',
    'Jamnagar',
    'Junagadh',
    'Visavadar',
    'Kapadvanj',
    'Kadi',
    'Visnagar',
    'Halvad',
    'Morbi',
    'Navsari',
    'Morva Hafad',
    'Harij',
    'Radhanpur',
    'Sami',
    'Siddhpur',
    'Porbandar',
    'Dhoraji',
    'Gondal(Veg.market Gondal)',
    'Jasdan',
    'Rajkot',
    'Rajkot(Veg.Sub Yard)',
    'Dhansura',
    'Surat',
    'Dasada Patadi',
    'Dhragradhra',
    'Vadhvan',
    'Padra',
    'Barara',
    'Shahzadpur',
    'Faridabad',
    'Gurgaon',
    'Indri',
    'Ladwa',
    'Narnaul',
    'Samalkha',
    'kalanwali',
    'Gohana',
    'Bilaspur',
    'Ashahipora (Anantnagh)',
    'Kulgam',
    'Zaloosa-Chararishrief (F&V)',
    'Akhnoor',
    'Batote',
    'Narwal Jammu (F&V)',
    'Kathua',
    'Rajouri (F&V)',
    'Parimpore',
    'Udhampur',
    'Chamaraj Nagar',
    'Laxmeshwar',
    'Mandya',
    'Aroor',
    'Chengannur',
    'Kayamkulam',
    'Mannar',
    'Angamaly',
    'Kothamangalam',
    'Mookkannur  VFPCK',
    'North Paravur',
    'Perumbavoor',
    'Thiruvaniyoor  VFPCK',
    'Thrippunithura',
    'Adimali',
    'Pazhayarikandam  VFPCK',
    'Thodupuzha',
    'Payyannur',
    'Thalasserry',
    'Neeleswaram',
    'Anchal',
    'Ettumanoor',
    'Pala',
    'Thalayolaparambu',
    'Palayam',
    'Perambra',
    'Thamarassery',
    'Kondotty',
    'Kottakkal',
    'Manjeri',
    'Thirurrangadi',
    'Koduvayoor',
    'Palakkad',
    'Pattambi',
    'Kuttoor',
    'Chavakkad',
    'Chelakkara',
    'Kodungalloor',
    'Kovilnada  VFPCK',
    'Neyyatinkara',
    'Parassala',
    'Alirajpur',
    'Anuppur',
    'Anjad',
    'Bhopal',
    'Rajnagar',
    'Damoh',
    'Dhamnod',
    'Dhar',
    'Gorakhpur',
    'Lashkar',
    'Itarsi',
    'Indore',
    'Bhikangaon',
    'Segaon',
    'Bichhiya',
    'Morena',
    'Chhapiheda',
    'Khilchipur',
    'Kurawar',
    'Narsinghgarh',
    'Pachaur',
    'Rewa',
    'Bina',
    'Sidhi',
    'Ujjain',
    'Umariya',
    'Sangamner',
    'Shevgaon',
    'Shrirampur',
    'Amrawati(Frui & Veg. Market)',
    'Beed',
    'Deoulgaon Raja',
    'Malkapur',
    'Chimur',
    'Chattrapati Sambhajinagar',
    'Paithan',
    'Dhule',
    'Armori',
    'Bhusaval',
    'Jalgaon',
    'Yawal',
    'Kolhapur',
    'Kalmeshwar',
    'Kamthi',
    'Nagpur',
    'Pune',
    'Pune(Moshi)',
    'Pune(Pimpri)',
    'Murud',
    'Pen',
    'Sangli',
    'Karad',
    'Satara',
    'Akluj',
    'Mangal Wedha',
    'Pandharpur',
    'Azadpur',
    'Hindol',
    'Kasinagar',
    'Parlakhemundi',
    'Jharsuguda',
    'Bhagta Bhai Ka',
    'Bhucho',
    'Raman',
    'Rampuraphul(Nabha Mandi)',
    'Jalalabad',
    'Dera Baba Nanak',
    'Dinanagar',
    'Gurdaspur',
    'Kalanaur',
    'Garh Shankar',
    'GarhShankar (Kotfatuhi)',
    'Tanda Urmur',
    'Shahkot',
    'Khanna',
    'Sahnewal',
    'Rajpura',
    'Ahmedgarh',
    'Naushera Pannuan',
    'Khajuwala',
    'Bundi',
    'Begu',
    'Sriganganagar (F&V)',
    'Suratgarh',
    'Rawatsar',
    'Bassi',
    'Jodhpur(F&V)(Paota)',
    'Dooni',
    'Ariyalur(Uzhavar Sandhai)',
    'Jeyankondam (Uzhavar Sandhai )',
    'Chengalpet(Uzhavar Sandhai )',
    'Guduvancheri(Uzhavar Sandhai )',
    'Jameenrayapettai(Uzhavar Sandhai )',
    'Madhuranthagam(Uzhavar Sandhai )',
    'Medavakkam(Uzhavar Sandhai )',
    'Pallavaram(Uzhavar Sandhai )',
    'Thirukalukundram(Uzhavar Sandhai )',
    'Kurichi(Uzhavar Sandhai )',
    'Mettupalayam(Uzhavar Sandhai )',
    'Pollachi(Uzhavar Sandhai )',
    'RSPuram(Uzhavar Sandhai )',
    'Singanallur(Uzhavar Sandhai )',
    'Sulur(Uzhavar Sandhai )',
    'Sundarapuram(Uzhavar Sandhai )',
    'Udumalpet',
    'Vadavalli(Uzhavar Sandhai )',
    'Chidambaram(Uzhavar Sandhai )',
    'Cuddalore(Uzhavar Sandhai )',
    'Panruti(Uzhavar Sandhai )',
    'Viruthachalam(Uzhavar Sandhai )',
    'AJattihalli(Uzhavar Sandhai )',
    'Dharmapuri(Uzhavar Sandhai )',
    'Harur(Uzhavar Sandhai )',
    'Palacode(Uzhavar Sandhai )',
    'Pennagaram(Uzhavar Sandhai )',
    'Chinnalapatti(Uzhavar Sandhai )',
    'Dindigul(Uzhavar Sandhai )',
    'Palani(Uzhavar Sandhai )',
    'Vedasanthur(Uzhavar Sandhai )',
    'Gobichettipalayam(Uzhavar Sandhai )',
    'Periyar Nagar(Uzhavar Sandhai )',
    'Perundurai(Uzhavar Sandhai )',
    'Sampath Nagar(Uzhavar Sandhai )',
    'Sathiyamagalam(Uzhavar Sandhai )',
    'Thalavadi(Uzhavar Sandhai )',
    'Kallakurichi(Uzhavar Sandhai )',
    'Sankarapuram(Uzhavar Sandhai )',
    'Kancheepuram(Uzhavar Sandhai )',
    'Kundrathur(Uzhavar Sandhai )',
    'Padappai(Uzhavar Sandhai )',
    'Karur(Uzhavar Sandhai )',
    'Kulithalai(Uzhavar Sandhai )',
    'Pallapatti (Uzhavar Sandhai )',
    'Velayuthampalayam(Uzhavar Sandhai )',
    'Avallapalli(Uzhavar Sandhai )',
    'Denkanikottai(Uzhavar Sandhai )',
    'Hosur(Uzhavar Sandhai )',
    'Kaveripattinam(Uzhavar Sandhai )',
    'Krishnagiri(Uzhavar Sandhai )',
    'Anaiyur(Uzhavar Sandhai )',
    'Anna nagar(Uzhavar Sandhai )',
    'Chokkikulam(Uzhavar Sandhai )',
    'Melur(Uzhavar Sandhai )',
    'Palanganatham(Uzhavar Sandhai )',
    'Thirumangalam(Uzhavar Sandhai )',
    'Usilampatty',
    'Mayiladuthurai(Uzhavar Sandhai )',
    'Nagapattinam(Uzhavar Sandhai )',
    'Sirkali(Uzhavar Sandhai )',
    'Myladi(Uzhavar Sandhai )',
    'Vadaseri',
    'Kumarapalayam(Uzhavar Sandhai )',
    'Mohanur(Uzhavar Sandhai )',
    'Namakkal(Uzhavar Sandhai )',
    'Paramathivelur(Uzhavar Sandhai )',
    'Rasipuram(Uzhavar Sandhai )',
    'Tiruchengode',
    'Perambalur(Uzhavar Sandhai )',
    'Alangudi(Uzhavar Sandhai )',
    'Aranthangi(Uzhavar Sandhai )',
    'Gandarvakottai(Uzhavar Sandhai )',
    'Karambakkudi(Uzhavar Sandhai )',
    'Pudukottai(Uzhavar Sandhai )',
    'Viralimalai(Uzhavar Sandhai )',
    'Paramakudi(Uzhavar Sandhai )',
    'Ramanathapuram(Uzhavar Sandhai )',
    'Arcot(Uzhavar Sandhai )',
    'Ranipettai(Uzhavar Sandhai )',
    'Ammapet(Uzhavar Sandhai )',
    'Athur(Uzhavar Sandhai )',
    'Attayampatti(Uzhavar Sandhai )',
    'Edapadi (Uzhavar Sandhai )',
    'Elampillai(Uzhavar Sandhai )',
    'Hasthampatti(Uzhavar Sandhai )',
    'Jalagandapuram(Uzhavar Sandhai )',
    'Mettur(Uzhavar Sandhai )',
    'Sooramangalam(Uzhavar Sandhai )',
    'Thammampatti (Uzhavar Sandhai )',
    'Thathakapatti(Uzhavar Sandhai )',
    'Devakottai (Uzhavar Sandhai )',
    'Karaikudi(Uzhavar Sandhai )',
    'Singampunari(Uzhavar Sandhai )',
    'Sivagangai (Uzhavar Sandhai )',
    'Tirupatthur(Uzhavar Sandhai )',
    'Sankarankoil(Uzhavar Sandhai )',
    'Tenkasi(Uzhavar Sandhai )',
    'Kumbakonam (Uzhavar Sandhai )',
    'Papanasam(Uzhavar Sandhai )',
    'Pattukottai(Uzhavar Sandhai )',
    'Thanjavur(Uzhavar Sandhai )',
    'Coonoor(Uzhavar Sandhai )',
    'Gudalur(Uzhavar Sandhai )',
    'Udhagamandalam(Uzhavar Sandhai )',
    'Andipatti(Uzhavar Sandhai )',
    'Bodinayakanur(Uzhavar Sandhai )',
    'Chinnamanur(Uzhavar Sandhai )',
    'Devaram(Uzhavar Sandhai )',
    'Kambam(Uzhavar Sandhai )',
    'Periyakulam(Uzhavar Sandhai )',
    'Theni(Uzhavar Sandhai )',
    'Lalgudi(Uzhavar Sandhai )',
    'Manachanallur(Uzhavar Sandhai )',
    'Manapparai(Uzhavar Sandhai )',
    'Musiri(Uzhavar Sandhai )',
    'Thuraiyur',
    'Ambasamudram(Uzhavar Sandhai )',
    'Kandiyaperi(Uzhavar Sandhai )',
    'Melapalayam(Uzhavar Sandhai )',
    'NGO Colony(Uzhavar Sandhai )',
    'Palayamkottai(Uzhavar Sandhai )',
    'Natrampalli(Uzhavar Sandhai )',
    'Vaniyampadi(Uzhavar Sandhai )',
    'Dharapuram(Uzhavar Sandhai )',
    'Kangayam(Uzhavar Sandhai )',
    'Palladam(Uzhavar Sandhai )',
    'Tiruppur (North) (Uzhavar Sandhai )',
    'Tiruppur (South) (Uzhavar Sandhai )',
    'Arani(Uzhavar Sandhai )',
    'Chengam(Uzhavar Sandhai )',
    'Cheyyar(Uzhavar Sandhai )',
    'Keelpennathur(Uzhavar Sandhai )',
    'Polur(Uzhavar Sandhai )',
    'Tamarainagar(Uzhavar Sandhai )',
    'Tiruvannamalai(Uzhavar Sandhai )',
    'Mannargudi I(Uzhavar Sandhai )',
    'Mannargudi II(Uzhavar Sandhai )',
    'Muthupettai(Uzhavar Sandhai )',
    'Needamangalam(Uzhavar Sandhai )',
    'Tiruthuraipoondi(Uzhavar Sandhai )',
    'Tiruvarur(Uzhavar Sandhai )',
    'Valangaiman',
    'Naravarikuppam(Uzhavar Sandhai )',
    'Paruthipattu(Uzhavar Sandhai )',
    'Perambakkam(Uzhavar Sandhai )',
    'Tiruvallur(Uzhavar Sandhai )',
    'Kovilpatti(Uzhavar Sandhai )',
    'Tuticorin(Uzhavar Sandhai )',
    'Gudiyatham(Uzhavar Sandhai )',
    'Kahithapattarai(Uzhavar Sandhai )',
    'Katpadi (Uzhavar Sandhai )',
    'Thirupathur',
    'Vellore',
    'Gingee(Uzhavar Sandhai )',
    'Tindivanam',
    'Ulundurpettai',
    'Aruppukottai(Uzhavar Sandhai )',
    'Kariyapatti(Uzhavar Sandhai )',
    'Rajapalayam(Uzhavar Sandhai )',
    'Sathur(Uzhavar Sandhai )',
    'Sivakasi(Uzhavar Sandhai )',
    'Srivilliputhur(Uzhavar Sandhai )',
    'Thalavaipuram(Uzhavar Sandhai )',
    'Virudhunagar(Uzhavar Sandhai )',
    'Adilabad',
    'Gudimalkapur',
    'L B Nagar',
    'Choppadandi',
    'Huzzurabad',
    'Karimnagar',
    'Burgampadu',
    'Wyra',
    'Mahbubnagar',
    'Wanaparthy town',
    'Zaheerabad',
    'Bhongir',
    'Huzurnagar',
    'Huzurnagar(Matampally)',
    'Kodad',
    'Suryapeta',
    'Tirumalagiri',
    'Kukatpally(Rythu Bazar)',
    'Mehndipatnam(Rythu Bazar)',
    'Hanmarkonda(Rythu Bazar)',
    'Warangal',
    'Chowmanu',
    'Kulai',
    'Pabiacherra',
    'Fatehabad',
    'Atrauli',
    'Dhanaura',
    'Hasanpur',
    'Baraut',
    'Bahraich',
    'Tulsipur',
    'Banda',
    'Barabanki',
    'Bahedi',
    'Richha',
    'Gulavati',
    'Sikanderabad',
    'Kamlaganj',
    'Jahanabad',
    'Sehjanwa',
    'Maudaha',
    'Shadabad',
    'Sikandraraau',
    'Ait',
    'Jalaun',
    'Mugrabaadshahpur',
    'Baruwasagar',
    'Mehrauni',
    'Bewar',
    'Mirzapur',
    'Muzzafarnagar',
    'Bachranwa',
    'Lalganj',
    'Puwaha',
    'Shahjahanpur',
    'Naugarh',
    'Sahiyapur',
    'Sitapur',
    'Bangarmau',
    'Roorkee',
    'Gadarpur',
    'Kicchha',
    'Sitarganj',
    'Indus(Bankura Sadar)',
    'Sainthia',
    'Karsiyang(Matigara)',
    'Siliguri',
    'Uluberia',
    'Ghatal',
    'Nadia',
    'Asansol',
    'Purulia',
    'Anakapally',
    'Pamohi(Garchuk)',
    'Haibargaon',
    'Jamui',
    'Gerabari, Korha Block',
    'Danapur',
    'Saidpurhat',
    'Jairamnagar',
    'Gattasilli',
    'Mahasamund',
    'Rajnandgaon',
    'Ponda',
    'Viramgam',
    'Babra',
    'Damnagar',
    'Dhari',
    'Anand(Veg,Yard,Anand)',
    'Dhanera',
    'Bodeliu',
    'Devgadhbaria',
    'Kalol(Veg,Market,Kalol)',
    'Unava',
    'Unjha',
    'Gogamba(Similiya)',
    'Jetpur(Dist.Rajkot)',
    'Himatnagar',
    'Khedbrahma',
    'Bardoli(Katod)',
    'Mahuva(Anaval)',
    'Vyra',
    'Gharaunda',
    'FerozpurZirkha(Nagina)',
    'Punhana',
    'New Grain Market , Panchkula',
    'Sonepat(Kharkhoda)',
    'Pulwama (F&V)',
    'Ganderbal',
    'Kolar',
    'Nedungapra  VFPCK',
    'Kannur',
    'Moothedam  VFPCK',
    'Ranniangadi',
    'Sendhwa',
    'Praswada',
    'Bijawar',
    'Kukshi',
    'Manawar',
    'Pipariya',
    'Petlawad',
    'Panna',
    'Chaakghat',
    'Shahagarh',
    'Nalkehda',
    'Shajapur',
    'Beohari',
    'Amarawati',
    'Gandchiroli',
    'Bhokardan',
    'Partur',
    'Pimpalgaon',
    'Yeola',
    'Alibagh',
    'Umarked(Danki)',
    'Goluwala',
    'Hanumangarh(Urlivas)',
    'Raniwara',
    'Nanganallur(Uzhavar Sandhai )',
    'Ambattur(Uzhavar Sandhai )',
    'Gopalraopet',
    'Manakodur',
    'Dammapet',
    'Alampur',
    'Narayanpet',
    'Devarakonda',
    'Devarkonda(Mallepalli)',
    'Miryalaguda',
    'Voligonda',
    'Jagnair',
    'Charra',
    'Akbarpur',
    'Babrala',
    'Shahaswan',
    'Najibabad',
    'Divai',
    'Jasvantnagar',
    'Farukhabad',
    'Fatehpur',
    'Banthara',
    'Ajuha',
    'Sirsa',
    'Sambhal',
    'Bankura Sadar',
    'Birbhum',
    'Aarah',
    'Tajpur',
    'Takhatpur',
    'Belarbahara',
    'Narayanpur',
    'Sarangarh',
    'Botad(Haddad)',
    'Mehsana',
    'Hodal',
    'Bumhama-Kupwara (F&V)',
    'Mohgaon',
    'LavKush Nagar(Laundi)',
    'Khirakiya',
    'Sehora',
    'Katni',
    'Pandhana',
    'Khargone',
    'Jeerapur',
    'Palari',
    'Agar',
    'Momanbadodiya',
    'Soyatkalan',
    'Sheopurkalan',
    'Vidisha',
    'Nagbhid',
    'Hingoli(Kanegoan Naka)',
    'Jalgaon(Masawat)',
    'Bhokar',
    'Pimpalgaon Baswant(Saykheda)',
    'Dumal',
    'Rayya',
    'Pudur',
    'Vemulawada',
    'Gadwal(Lezza)',
    'Neredcherla',
    'Ramannapet',
    'Silachhari',
    'Achnera',
    'Wazirganj',
    'Bijnaur',
    'Kayamganj',
    'Kadaura',
    'Vilaspur',
    'Bhehjoi',
    'Nanakmatta',
    'Jainagar',
    'Natwar',
    'Nokha',
    'Bhatgaon',
    'Kasdol',
    'Boraee',
    'Nagari',
    'Amadula',
    'Champa',
    'Korar',
    'Lakhanpuri',
    'Narharpur',
    'Sambalpur',
    'Gandai',
    'Modasar',
    'Bachau',
    'Rajpipla',
    'Nizar(Kukarmuda)',
    'Nizar(Pumkitalov)',
    'Savanur',
    'Jabalpur',
    'Khandwa',
    'Raisen',
    'Sagar',
    'Niwadi',
    'Badnagar',
    'Sangola',
    'Nimapara',
    'Surajgarh',
    'Bhainsa',
    'Chinnoar',
    'Mallial(Cheppial)',
    'Peddapalli',
    'Nelakondapally',
    'Sattupalli',
    'Devarkonda(Dindi)',
    'Visoli',
    'Etawah',
    'Kurara',
    'Kalpi',
    'Madhogarh',
    'Mauranipur',
    'Mahoba',
    'Bazpur',
    'Madanapalli',
    'Punganur',
    'Forbesganj',
    'Sakri',
    'Belargaon',
    'Bhanupratappur',
    'Bededonger',
    'Katghora',
    'Manendragarh',
    'Jhalap',
    'Gogamba',
    'Nizar',
    'Loharu',
    'Cheeka',
    'Vellarada  VFPCK',
    'Jobat',
    'Sonkatch',
    'Badnawar',
    'Dindori',
    'Sanawad',
    'Mandla',
    'Mehar',
    'Ashta',
    'Badod',
    'Karera',
    'Ganjbasoda',
    'Rahuri',
    'Chandvad',
    'Lasalgaon',
    'Lasalgaon(Vinchur)',
    'Chogawan',
    'Charla',
    'Devarakadra',
    'Huzumnagar(Garidepally)',
    'Sandila',
    'Tanakpurs'
  ];

  List<String> Commodity = [
    "Bitter gourd",
    "Capsicum",
    "Pumpkin",
    "Cabbage",
    "Brinjal",
    "Green Chilli",
    "Bottle gourd",
    "Tomato",
    "Bhindi(Ladies Finger)",
    "Lemon",
    "Onion",
    "Paddy(Dhan)(Common)",
    "Carrot",
    "Potato",
    "Raddish",
    "Coconut",
    "Black Gram (Urd Beans)(Whole)",
    "Castor Seed",
    "Groundnut",
    "Bengal Gram(Gram)(Whole)",
    "Cotton",
    "Jowar(Sorghum)",
    "Sesamum(Sesame,Gingelly,Til)",
    "Soyabean",
    "Wheat",
    "Bajra(Pearl Millet/Cumbu)",
    "Mustard",
    "Cauliflower",
    "Chikoos(Sapota)",
    "Guar",
    "Green Gram (Moong)(Whole)",
    "Methi Seeds",
    "Cluster beans",
    "Coriander(Leaves)",
    "Cowpea(Veg)",
    "Ginger(Green)",
    "Mint(Pudina)",
    "Cummin Seed(Jeera)",
    "Kulthi(Horse Gram)",
    "Ajwan",
    "Banana",
    "Suva (Dill Seed)",
    "Kabuli Chana(Chickpeas-White)",
    "Methi(Leaves)",
    "Papaya",
    "Arhar (Tur/Red Gram)(Whole)",
    "Corriander seed",
    "Maize",
    "Papaya (Raw)",
    "Peas cod",
    "Pointed gourd (Parval)",
    "Surat Beans (Papadi)",
    "Elephant Yam (Suran)",
    "Spinach",
    "Cucumbar(Kheera)",
    "Drumstick",
    "Sponge gourd",
    "Mousambi(Sweet Lime)",
    "Apple",
    "Pomegranate",
    "Ridgeguard(Tori)",
    "Banana - Green",
    "Knool Khol",
    "Garlic",
    "Lotus Sticks",
    "Peas Wet",
    "Round gourd",
    "Orange",
    "Pear(Marasebu)",
    "Beetroot",
    "Gur(Jaggery)",
    "Snakeguard",
    "Field Pea",
    "Little gourd (Kundru)",
    "Tapioca",
    "Amla(Nelli Kai)",
    "Black pepper",
    "Pineapple",
    "Indian Beans (Seam)",
    "Amphophalus",
    "Colacasia",
    "Leafy Vegetable",
    "Grapes",
    "Ashgourd",
    "Cloves",
    "Rice",
    "Rubber",
    "Coconut Seed",
    "Amaranthus",
    "Copra",
    "Mango (Raw-Ripe)",
    "Betal Leaves",
    "French Beans (Frasbean)",
    "Chili Red",
    "Lime",
    "Sweet Potato",
    "Duster Beans",
    "Beans",
    "Linseed",
    "gulli",
    "Green Gram Dal (Moong Dal)",
    "Lentil (Masur)(Whole)",
    "Guava",
    "Seetapal",
    "Chilly Capsicum",
    "Onion Green",
    "Water Melon",
    "Ginger(Dry)",
    "Ox",
    "Mango",
    "Marigold(loose)",
    "Green Avare (W)",
    "Rose(Local)",
    "Thondekai",
    "Tender Coconut",
    "Chow Chow",
    "Mashrooms",
    "Custard Apple (Sharifa)",
    "Yam (Ratalu)",
    "Green Peas",
    "Tamarind Fruit",
    "Jack Fruit",
    "Turnip",
    "Fig(Anjura/Anjeer)",
    "Jasmine",
    "Marigold(Calcutta)",
    "Tube Rose(Loose)",
    "Karbuja(Musk Melon)",
    "Jamun(Narale Hannu)",
    "Tube Flower",
    "Kakada",
    "Kankambra",
    "Wood",
    "Cowpea (Lobia/Karamani)",
    "Masur Dal",
    "Mustard Oil",
    "White Peas",
    "Barley (Jau)",
    "Bengal Gram Dal (Chana Dal)",
    "Arhar Dal(Tur Dal)",
    "Sweet Pumpkin",
    "Squash(Chappal Kadoo)",
    "Arecanut(Betelnut/Supari)",
    "Guar Seed(Cluster Beans Seed)",
    "Groundnut (Split)",
    "Isabgul (Psyllium)",
    "Soanf",
    "Ground Nut Seed",
    "Pegeon Pea (Arhar Fali)",
    "Tinda",
    "Kinnow",
    "Alasande Gram",
    "Dry Grapes",
    "Gladiolus Cut Flower",
    "Jarbara",
    "Fish",
    "Sugar",
    "Peas(Dry)",
    "Black Gram Dal (Urd Dal)",
    "Mahua",
    "Tamarind Seed",
    "Taramira",
    "Kartali (Kantola)",
    "Walnut",
    "Coconut Oil",
    "Nutmeg",
    "Pepper ungarbled",
    "Ragi (Finger Millet)",
    "buttery",
    "Kutki",
    "Same/Savi",
    "Chakotha",
    "Cashewnuts",
    "Astera",
    "Carnation",
    "Jute",
    "Gram Raw(Chholia)",
    "Turmeric (raw)",
    "Alsandikai",
    "Cardamoms",
    "Cocoa",
    "Other green and fresh vegetables",
    "Goat",
    "Hen",
    "Long Melon(Kakri)",
    "Lilly",
    "Moath Dal",
    "Rajgir",
    "Millets",
    "Groundnut pods (raw)",
    "Mataki",
    "Kodo Millet(Varagu)",
    "Rose(Loose)",
  ];

  List<String> variety = [];
}
